//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.18033
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrystalMpq.Explorer.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>.txt|CrystalMpq.Explorer.Viewers.TextViewer, CrystalMpqExplorer, Version=1" +
            ".7.0.0, Culture=neutral, PublicKeyToken=null</string>\r\n  <string>.ini|CrystalMpq" +
            ".Explorer.Viewers.TextViewer, CrystalMpqExplorer, Version=1.7.0.0, Culture=neutr" +
            "al, PublicKeyToken=null</string>\r\n  <string>.wtf|CrystalMpq.Explorer.Viewers.Tex" +
            "tViewer, CrystalMpqExplorer, Version=1.7.0.0, Culture=neutral, PublicKeyToken=nu" +
            "ll</string>\r\n  <string>.lst|CrystalMpq.Explorer.Viewers.TextViewer, CrystalMpqEx" +
            "plorer, Version=1.7.0.0, Culture=neutral, PublicKeyToken=null</string>\r\n  <strin" +
            "g>.sbt|CrystalMpq.Explorer.Viewers.TextViewer, CrystalMpqExplorer, Version=1.7.0" +
            ".0, Culture=neutral, PublicKeyToken=null</string>\r\n  <string>.toc|CrystalMpq.Exp" +
            "lorer.Viewers.TextViewer, CrystalMpqExplorer, Version=1.7.0.0, Culture=neutral, " +
            "PublicKeyToken=null</string>\r\n  <string>.css|CrystalMpq.Explorer.Viewers.TextVie" +
            "wer, CrystalMpqExplorer, Version=1.7.0.0, Culture=neutral, PublicKeyToken=null</" +
            "string>\r\n  <string>.htm|CrystalMpq.Explorer.Viewers.TextViewer, CrystalMpqExplor" +
            "er, Version=1.7.0.0, Culture=neutral, PublicKeyToken=null</string>\r\n  <string>.h" +
            "tml|CrystalMpq.Explorer.Viewers.TextViewer, CrystalMpqExplorer, Version=1.7.0.0," +
            " Culture=neutral, PublicKeyToken=null</string>\r\n  <string>.xml|CrystalMpq.Explor" +
            "er.Viewers.TextViewer, CrystalMpqExplorer, Version=1.7.0.0, Culture=neutral, Pub" +
            "licKeyToken=null</string>\r\n  <string>.lua|CrystalMpq.Explorer.Viewers.TextViewer" +
            ", CrystalMpqExplorer, Version=1.7.0.0, Culture=neutral, PublicKeyToken=null</str" +
            "ing>\r\n  <string>.js|CrystalMpq.Explorer.Viewers.TextViewer, CrystalMpqExplorer, " +
            "Version=1.7.0.0, Culture=neutral, PublicKeyToken=null</string>\r\n  <string>.xsl|C" +
            "rystalMpq.Explorer.Viewers.TextViewer, CrystalMpqExplorer, Version=1.7.0.0, Cult" +
            "ure=neutral, PublicKeyToken=null</string>\r\n  <string>.ttf|CrystalMpq.Explorer.Vi" +
            "ewers.FontViewer, CrystalMpqExplorer, Version=1.7.0.0, Culture=neutral, PublicKe" +
            "yToken=null</string>\r\n  <string>.bmp|CrystalMpq.Explorer.Viewers.BitmapViewer, C" +
            "rystalMpqExplorer, Version=1.7.0.0, Culture=neutral, PublicKeyToken=null</string" +
            ">\r\n  <string>.jpg|CrystalMpq.Explorer.Viewers.BitmapViewer, CrystalMpqExplorer, " +
            "Version=1.7.0.0, Culture=neutral, PublicKeyToken=null</string>\r\n  <string>.jpeg|" +
            "CrystalMpq.Explorer.Viewers.BitmapViewer, CrystalMpqExplorer, Version=1.7.0.0, C" +
            "ulture=neutral, PublicKeyToken=null</string>\r\n  <string>.png|CrystalMpq.Explorer" +
            ".Viewers.BitmapViewer, CrystalMpqExplorer, Version=1.7.0.0, Culture=neutral, Pub" +
            "licKeyToken=null</string>\r\n  <string>.gif|CrystalMpq.Explorer.Viewers.BitmapView" +
            "er, CrystalMpqExplorer, Version=1.7.0.0, Culture=neutral, PublicKeyToken=null</s" +
            "tring>\r\n  <string>.blp|CrystalMpq.Explorer.BaseViewers.BLPViewer, CrystalMpq.Exp" +
            "lorer.BaseViewers, Version=1.5.0.0, Culture=neutral, PublicKeyToken=null</string" +
            ">\r\n  <string>.dbc|CrystalMpq.Explorer.BaseViewers.ClientDatabaseViewer, CrystalM" +
            "pq.Explorer.BaseViewers, Version=1.5.0.0, Culture=neutral, PublicKeyToken=null</" +
            "string>\r\n  <string>.wav|CrystalMpq.Explorer.AudioVideo.MediaPlayer, CrystalMpq.E" +
            "xplorer.AudioVideo, Version=2.5.0.0, Culture=neutral, PublicKeyToken=null</strin" +
            "g>\r\n  <string>.mp3|CrystalMpq.Explorer.AudioVideo.MediaPlayer, CrystalMpq.Explor" +
            "er.AudioVideo, Version=2.5.0.0, Culture=neutral, PublicKeyToken=null</string>\r\n " +
            " <string>.ogg|CrystalMpq.Explorer.AudioVideo.MediaPlayer, CrystalMpq.Explorer.Au" +
            "dioVideo, Version=2.5.0.0, Culture=neutral, PublicKeyToken=null</string>\r\n  <str" +
            "ing>.avi|CrystalMpq.Explorer.AudioVideo.MediaPlayer, CrystalMpq.Explorer.AudioVi" +
            "deo, Version=2.5.0.0, Culture=neutral, PublicKeyToken=null</string>\r\n</ArrayOfSt" +
            "ring>")]
        public global::System.Collections.Specialized.StringCollection ViewerAssociations {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ViewerAssociations"]));
            }
            set {
                this["ViewerAssociations"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SlateGray")]
        public global::System.Drawing.Color ViewerBackColor {
            get {
                return ((global::System.Drawing.Color)(this["ViewerBackColor"]));
            }
            set {
                this["ViewerBackColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("utf-8")]
        public string TextViewerDefaultEncoding {
            get {
                return ((string)(this["TextViewerDefaultEncoding"]));
            }
            set {
                this["TextViewerDefaultEncoding"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Plugins")]
        public string PluginsDirectory {
            get {
                return ((string)(this["PluginsDirectory"]));
            }
            set {
                this["PluginsDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ExtractionDirectory {
            get {
                return ((string)(this["ExtractionDirectory"]));
            }
            set {
                this["ExtractionDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ExtractionOverwriteFiles {
            get {
                return ((bool)(this["ExtractionOverwriteFiles"]));
            }
            set {
                this["ExtractionOverwriteFiles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ExtractionRecurse {
            get {
                return ((bool)(this["ExtractionRecurse"]));
            }
            set {
                this["ExtractionRecurse"] = value;
            }
        }
    }
}
